linux tools
·samba (mounting Linux on Windows)
·tmux and screen (persistent shell sessions)
·all the standard UNIX utilities (awk, sed, grep, head, tail, uniq, sort, etc.)
·perl (rapid prototyping, quick hacks, one-liners)
·iptables and nftables (firewalling)
·htop (better top)
·mtr (better traceroute)
·multitail (tail multiple files in multiple windows)
·nc (netcat, TCP/IP swiss army knife)
·iftop (bandwidth monitor)
·ack (better grep)
·ipcalc (network address calculator)
·pv (pipe viewer – UNIX pipe progress bar)
·rsync (backups)
·ncdu (disk space visualization)
·curl (http client)
·nmap (network scanner)
·tcpdump and wireshark (for network debugging)
·sysdig (strace + lsof + tcpdump combined)
·youtube-dl (downloading all online videos)
 
 #vim 
·surround.vim (quickly edit surrounding text)
·repeat.vim (repeat surround commands)
·matchit.vim (extend what % key matches)
·snipmate.vim (code snippets)
·nerd_tree.vim (explore filesystem from vim)
·a.vim (alternate C and H files)
·ragtag.vim (mappings for editing HTML)
·tabular.vim (aligning text)
·bufexplorer.vim (working with buffers)
·python.vim (better python support)
·exchange.vim (exchange text quickly)
·abolish.vim (substitute words)
·speeddating.vim (increment dates)

#windows tools
·Total Commander (file manager)
·Visual Studi(can’t beat IntelliSense)
·SQLyog (GUI manager for MySQL databases)
·SQLiteSpy (GUI manager for SQLite databases)
·pgAdmin (GUI manager for Postrgres databases)
·WinSCP and SecureFX (secure FTP clients)
·Putty and SecureCRT (SSH clients)
·KeePass (password manager)
·ClipX (clipboard manager)
·Launchy (program launcher)
·Locate32 (file indexer)
·allSnap (window manager)
·AutoHotkeys (automate tasks and programs)
·Virtual CloneDrive (mount disk images)
·IsoBuster (extract disk images)
·ImgBurn (image burner)
·Enounce MySpeed​​ (speedup or slow down videos)
·Hex Workshop (hex editor)
·VMWare Workstation (virtual machines)
·Cygwin (unix tools)
·UltraMon (multi-screen support)
·Beyond Compare (diffing tool)
·Tclock2 (better clock)
·Fineprint (printer proxy)
·SumatraPDF (better PDF viewer)
·AviSynth (edit videos programmatically)
·ffmpeg (convert videos)
·VirtualDub (convert and edit videos)
·WinDirStat (disk space visualization)
·clink (better cmd.exe)
·IDA Pr(debugging)
·Photoshop
·Sysinternals tools
